Nav bar
YoelAharoni12/yoelTraining1 pull request #1
Opened 2021-11-09 14:43 UTC by YoelAharoni12

Finish semantic exrc

2021-11-10 15:38 UTC, rongoldinfeld requested changes

2021-11-10 15:38 UTC, rongoldinfeld commented on .gitignore
> +/package-lock.json
yes he sholud be in gitignore
and when we install a new library with npm, it Updated automatically.

2021-11-10 19:30 UTC, YoelAharoni12 commented on src/style/index.less
> +  &:hover {
represents the current selector parent, it also give u an options to do nesting with your element

2021-11-14 08:58 UTC, rongoldinfeld requested changes

2021-11-14 08:58 UTC, rongoldinfeld commented on src/scripts/Jquey.js
> +console.log($('.ui .menu'))
remove console.log

2021-11-14 08:58 UTC, rongoldinfeld commented on src/style/index.less
> +@padding: 0 !important;
remove important from variable declaration

2021-11-14 10:16 UTC, rongoldinfeld commented on .gitignore
> +/package-lock.json
package-lock should be part of the project: 
1. provides security 
2. verifies which versions you actually installed

2021-11-14 10:56 UTC, rongoldinfeld requested changes

2021-11-14 10:56 UTC, rongoldinfeld commented on .gitignore
> +/semantic/dist/
keep semantic css files but remove css,.map files from your src

2021-11-14 10:56 UTC, rongoldinfeld commented on src/style/index.less
> +  color: #FF4500 !important;
need the important?

2021-11-14 10:56 UTC, rongoldinfeld commented on src/style/index.less
> +  content: "\20AA" !important;
need the important?

2021-11-14 10:56 UTC, rongoldinfeld commented on src/amaRomach/index.html
> +                        <button class="ui icon romach secondary button">
inside src folder create two folders:
1. home includes: home.html, home.css
2. card includes: cart.html, cart.less

2021-11-14 10:56 UTC, rongoldinfeld commented on src/style/index.less
> +.shekel-label::after{
what does 
@siteFolder  : 'site';
@site       : 'amazon';

mean in theme.config?

2021-11-14 10:56 UTC, rongoldinfeld commented on src/style/index.less
> +.shekel-label::after{
why do u need the .min.css files?

2021-11-15 13:25 UTC, rongoldinfeld commented on src/amaRomach/index.html
> +<!DOCTYPE html>
DONE!

2021-11-16 15:12 UTC, merged